// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDni1A2N5sUG65My8lyJ6KSQw9ywmQFLh0',
    appId: '1:776305978149:web:fc456b3f846dffc80408cc',
    messagingSenderId: '776305978149',
    projectId: 'semster-project-17412',
    authDomain: 'semster-project-17412.firebaseapp.com',
    storageBucket: 'semster-project-17412.appspot.com',
    measurementId: 'G-NFKTDW93DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb_oWS6foGnony_oswDO4aExgjPDpANSk',
    appId: '1:776305978149:android:1a3a6cfb24609ff50408cc',
    messagingSenderId: '776305978149',
    projectId: 'semster-project-17412',
    storageBucket: 'semster-project-17412.appspot.com',
  );
}
